namespace Hermes.Runtime;

public sealed record NightlyResearchState(
    string StateVersion,
    DateTimeOffset UpdatedAtUtc,
    string Status,
    string RunId,
    DateTimeOffset? StartedAtUtc,
    DateTimeOffset? DeadlineUtc,
    int IterationsCompleted,
    int IdleIterations,
    int WorkPerformed,
    string NextAction,
    string? LastCheckpointPath,
    string? LastAutopilotReportPath,
    string? LastError,
    bool NoAutoTrading,
    bool HumanReviewRequired,
    DateTimeOffset? NextScheduledStartUtc = null,
    DateTimeOffset? LastStartUtc = null,
    DateTimeOffset? LastStopUtc = null,
    bool CurrentlyRunning = false,
    double RuntimeDurationMinutes = 0,
    int? ProcessId = null,
    DateTimeOffset? StopRequestedAtUtc = null,
    bool? CognitiveJobsEnabled = null,
    DateTimeOffset? LastKnowledgeScanUtc = null,
    DateTimeOffset? LastQueueProcessedUtc = null,
    DateTimeOffset? LastCognitiveInsightsUtc = null,
    int? QueuedResearchItems = null,
    IReadOnlyList<string>? ActiveDomains = null,
    string? LastCognitiveError = null,
    string? LastCognitiveSummaryPath = null);
