namespace Hermes.Runtime;

public sealed record OosQualityImprovementExperiment(
    string ExperimentId,
    DateTimeOffset CreatedAtUtc,
    string TargetStrategyId,
    string StrategyFamily,
    string? PatternId,
    string Symbol,
    string Timeframe,
    int PriorityRank,
    double SourceNearMissScore,
    IReadOnlyList<string> AddressedBlockers,
    IReadOnlyList<string> ProposedFilters,
    string WalkForwardPlan,
    IReadOnlyList<string> RollingValidationWindows,
    string ExpectedImpact,
    bool NoTradingExecution,
    bool HumanReviewRequired);

public sealed record CostResilienceExperiment(
    string ExperimentId,
    DateTimeOffset CreatedAtUtc,
    string TargetStrategyId,
    string StrategyFamily,
    string? PatternId,
    string Symbol,
    string Timeframe,
    int PriorityRank,
    double SourceNearMissScore,
    IReadOnlyList<string> AddressedBlockers,
    IReadOnlyList<string> ProposedFilters,
    double MinimumMoveToCostRatio,
    string SpreadStressScenario,
    string SlippageStressScenario,
    IReadOnlyList<string> AvoidSessions,
    string ExpectedImpact,
    bool NoTradingExecution,
    bool HumanReviewRequired);

public sealed record RiskSensitivityExperiment(
    string ExperimentId,
    DateTimeOffset CreatedAtUtc,
    string TargetStrategyId,
    string StrategyFamily,
    string? PatternId,
    string Symbol,
    string Timeframe,
    int PriorityRank,
    double SourceNearMissScore,
    IReadOnlyList<string> AddressedBlockers,
    IReadOnlyList<double> RiskProfiles,
    string MaxTradeFrequencyHint,
    string DrawdownControl,
    double TargetRuinProbability,
    string ExpectedImpact,
    bool NoTradingExecution,
    bool HumanReviewRequired);

public sealed record RegimeSessionFilterExperiment(
    string ExperimentId,
    DateTimeOffset CreatedAtUtc,
    string TargetStrategyId,
    string StrategyFamily,
    string? PatternId,
    string Symbol,
    string Timeframe,
    int PriorityRank,
    double SourceNearMissScore,
    IReadOnlyList<string> AddressedBlockers,
    IReadOnlyList<string> PreferredRegimes,
    IReadOnlyList<string> AvoidedRegimes,
    IReadOnlyList<string> PreferredSessions,
    IReadOnlyList<string> AvoidedSessions,
    string VolatilityFilter,
    string ExpectedImpact,
    bool NoTradingExecution,
    bool HumanReviewRequired);

public sealed record QualityImprovementExperimentReport(
    string ReportId,
    DateTimeOffset CreatedAtUtc,
    int CandidatesAnalyzed,
    int BaselineNearMissCount,
    int BatchSize,
    IReadOnlyList<string> BlockersAddressed,
    IReadOnlyList<string> ExpectedBlockerReduction,
    IReadOnlyList<OosQualityImprovementExperiment> OosExperiments,
    IReadOnlyList<CostResilienceExperiment> CostResilienceExperiments,
    IReadOnlyList<RiskSensitivityExperiment> RiskSensitivityExperiments,
    IReadOnlyList<RegimeSessionFilterExperiment> RegimeSessionFilterExperiments,
    bool NearMissCountChanged,
    string NearMissImpactNote,
    bool NoCandidateApprovalForced,
    bool NoTradingExecution,
    bool NoBrokerAction,
    bool NoAutoTrading,
    bool HumanReviewRequired);
