namespace Hermes.Runtime;

public sealed record SimulationPerformanceMetrics(
    double NetR,
    double SharpeRatio,
    double ProfitFactor,
    double MaxDrawdown,
    double Expectancy,
    int ConsecutiveLosses,
    double StabilityScore,
    double Winrate,
    int TradeCount,
    double GrossProfitR = 0,
    double EstimatedCostR = 0,
    double RobustnessScore = 0,
    double GrossR = 0,
    double FeesR = 0,
    double SlippageR = 0,
    double RealismPenalty = 0,
    double RobustnessConfidence = 0,
    double ParameterStability = 0,
    double SampleQuality = 0,
    double OverfitRisk = 0,
    double RealismScore = 0,
    string RealismPenaltyReason = "",
    bool TooGoodToBeTrue = false,
    double CostSensitivity = 0,
    double LossDistributionQuality = 0);
