namespace Hermes.Runtime;

public sealed record StrategyEvolutionSummary(
    string SummaryVersion,
    DateTimeOffset GeneratedAtUtc,
    IReadOnlyList<StrategyResearchResult> TopStrategies,
    IReadOnlyList<StrategyResearchResult> WeakStrategies,
    IReadOnlyList<string> BestSymbols,
    IReadOnlyList<string> BestTimeframes,
    IReadOnlyList<string> StabilityMetrics,
    IReadOnlyList<string> FitnessTrends,
    IReadOnlyList<string> ExplorationCoverage,
    IReadOnlyList<string> StrategyRankings,
    IReadOnlyList<string> ParameterStatistics,
    IReadOnlyList<string> TimeframeComparisons,
    IReadOnlyList<StrategyCluster> Clusters,
    bool NoAutoTrading,
    bool HumanReviewRequired,
    IReadOnlyList<string>? BestPatterns = null,
    IReadOnlyList<string>? WeakPatterns = null,
    IReadOnlyList<string>? AvoidCombinations = null,
    IReadOnlyList<string>? NextRecommendedTests = null,
    IReadOnlyList<string>? SourcePerformance = null,
    IReadOnlyList<string>? BestTradingDePatterns = null,
    IReadOnlyList<string>? RobustStrategies = null,
    IReadOnlyList<string>? OverfitSuspectedStrategies = null,
    IReadOnlyList<string>? HighRiskStrategies = null,
    IReadOnlyList<string>? StableSymbolTimeframeCombinations = null,
    IReadOnlyList<string>? BestRegimes = null,
    IReadOnlyList<string>? WeakRegimes = null,
    IReadOnlyList<string>? PreferredSessions = null,
    IReadOnlyList<string>? AvoidSessions = null,
    IReadOnlyList<string>? VolatilityPreference = null,
    double? RegimeConsistencyScore = null,
    IReadOnlyList<string>? PreferredRegimes = null,
    IReadOnlyList<string>? AvoidedRegimes = null,
    IReadOnlyList<string>? TooGoodToBeTrueStrategies = null,
    IReadOnlyList<string>? CostSensitiveStrategies = null,
    IReadOnlyList<string>? CostSensitivitySummary = null,
    IReadOnlyList<string>? RobustGateSummary = null);
