namespace Hermes.Runtime;

public sealed record WalkForwardStrategyAssessment(
    string StrategyVariantId,
    string StrategyFamily,
    string? PatternId,
    double TrainScore,
    double ValidationScore,
    double OutOfSampleScore,
    string StrategyConfidence,
    IReadOnlyList<string> OverfitFlags,
    bool Robust,
    bool HighRisk,
    double TrainPerformance = 0,
    double ValidationPerformance = 0,
    double DegradationScore = 0,
    double RobustnessGap = 0,
    double RealismPenalty = 0,
    double RobustnessConfidence = 0,
    double ParameterStability = 0,
    double SampleQuality = 0,
    double OverfitRisk = 0,
    double RealismScore = 0,
    string RealismPenaltyReason = "",
    bool TooGoodToBeTrue = false,
    double CostSensitivity = 0,
    double LossDistributionQuality = 0,
    bool OosAvailable = false,
    double WalkForwardConfidence = 0,
    double RegimeConsistencyScore = 0,
    IReadOnlyList<string>? PreferredRegimes = null,
    IReadOnlyList<string>? AvoidedRegimes = null,
    double RegimeSampleQuality = 0);
